name: Deploy # Make sure there's a name

on:
  push:
    branches:
      - "*" # This should catch all branches

jobs:
  test-trigger: # Simple test job
    runs-on: ubuntu-latest
    steps:
      - name: Test Step
        run: echo "This workflow was triggered"
